### ISSUE TITLE
Desarrollo de la documentacion

### ISSUE THREAD

**Issue by RenardCoffee** [Sheeenpai/ProyectoFinalSP#4]

**Comment by VenegasMissael** [comment]
## Antecedentes

El concepto de la domótica se remonta hasta principios del siglo XX, esto debido a la invención de los electrodomésticos como primeras máquinas colaboradoras en la realización de labores del hogar. Fue en los 50’s cuando se desarrolla la primera casa automatizada llamada “The push-button Manor”.

No fue hasta los 90’s, cuando el internet afectaría de sobremanera el desarrollo de la domótica debido a la normalización del internet, y a partir de los años 2000, el internet de las cosas se fue integrando poco a poco a cada aspecto del hogar.

En el 2016, Mark Zuckerberg logró desarrollar una IA llamada “Jarvis” que podría hacerse cargo de diversas tareas del hogar tan sólo con pedirlo con la voz.

## Objetivos.

* Objetivos especificos

1. Lograr la comunicación entre el Sensor y el arduino.
2. Hacer que el LCD puede mostrar nuestro mensaje de verificación.
3. Lograr activar el motor mediante, activación por el sensor PIR.

* Objetivos generales.
1. Lograr que el circuito funcione.
2. Conocer más sobre el uso de microcontroladores en la domótica.
