### ISSUE TITLE
Determinar los sensores a utilizar

### ISSUE THREAD

**Issue by RenardCoffee** [Sheeenpai/ProyectoFinalSP#7]

**Comment by RenardCoffee** [comment]
# Sensores a utilizar:
* Sensor PIR.
* Pantalla LDC 16x2.

**Comment by VenegasMissael** [comment]
![image](https://user-images.githubusercontent.com/38516741/83320630-21429c00-a1fe-11ea-85ce-6fe319bf92a8.png)
![image](https://user-images.githubusercontent.com/38516741/83320637-328ba880-a1fe-11ea-8066-74bd0d0f0f07.png)
