### ISSUE TITLE
Pruebas de la simulación.

### ISSUE THREAD

**Issue by RenardCoffee** [Sheeenpai/ProyectoFinalSP#9]

**Comment by prisskawaii** [comment]
### **PRUEBAS DE LA SIMULACIÓN**
![ ](https://github.com/Sheeenpai/ProyectoFinalSP/blob/master/Imagenes/pruebaCircuito.gif?raw=true")

### **Enlace**
[Circuito]( https://www.tinkercad.com/things/0dwzmHiTWbz )
